[[language]]
name = "rust"

[language-server.rust-analyzer.config]
check.overrideCommand = [
  "cargo",
  "component",
  "check",
  "--workspace",
  "--all-targets",
  "--message-format=json",
]
cargo.buildScripts.overrideCommand = [
  "cargo",
  "component",
  "check",
  "--workspace",
  "--all-targets",
  "--message-format=json",
]
