package ss:responder@0.1.0;

interface ckcompact-dr-kdf {
    kdf-rk: func(rk: list<u8>, dh-out: list<u8>, info: list<u8>) -> tuple<list<u8>, list<u8>>;
    kdf-ck: func(ck: list<u8>) -> tuple<list<u8>, list<u8>>;
}

// Component crypto functions
world ckcompact-dr-kdf-world {
    import ckcompact-dr-kdf;
    export ckcompact-dr-kdf;
}

