// Component crypto functions
package ss:crypto@0.1.0;

interface ck-compact-kdf {
    kdf-rk: func(rk: list<u8>, dh-out: list<u8>, info: list<u8>) -> tuple<list<u8>, list<u8>>;
    kdf-ck: func(ck: list<u8>) -> tuple<list<u8>, list<u8>>;
}

world crypto {
    export ck-compact-kdf ;
}

